version: "3.8"

services:
  react-app-dockerize:
    container_name: react-app-dockerize_c

    # Build the image using the Dockerfile in the same folder
    build:
      context: ..        # <-- Go up one level to root of repo
      dockerfile: docker/Dockerfile  # <-- path relative to context

    # Map host port 5002 to container port 5002
    ports:
      - "5002:5002"

    # Mount the app code into the container
    volumes:
      - ../:/app
      - /app/node_modules

    # Command to run React dev server
    command: npm run dev
