services:
  jenkins:
    build:
      context: ..
      dockerfile: docker/jenkins.Dockerfile
    image: custom-jenkins-node   # 👈 IMPORTANT
    container_name: jenkins_c
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_home: