jenkins:
  systemMessage: "Jenkins ready with auto pipeline"
  numExecutors: 2

unclassified:
  location:
    url: "http://localhost:8080/"

jobs:
  - script: >
      pipelineJob('ReactApp-Portfolio') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/saqib769/devops-portfolio.git')
                }
                branch('main')
              }
            }
            scriptPath('jenkins/Jenkinsfile')  # your Jenkinsfile location
          }
        }
      }